server {
    listen 80;
    server_name localhost;

    # 프론트엔드
    location / {
        proxy_pass http://gordi-frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 백엔드 API
    location /api/ {
        proxy_pass http://gordi-backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}