version: '3.8'

services:
  spring-backend:
    build:
      context: ./backend      # 백엔드 Dockerfile이 위치한 경로
      dockerfile: Dockerfile
    image: spring-backend:latest
    container_name: spring-backend
    ports:
      - "8080:8080"
    env_file:
      - /home/ubuntu/env/backend.env  # EC2 호스트의 환경변수 절대경로
    networks:
      - app-network

networks:
  app-network:
    external: true  # 기존 app-network를 함께 공유